### ISSUE TITLE
Unable to distinguish values from different fields sharing the same ItemKey

### ISSUE THREAD

**Issue by uklotzde** [Serial-ATA/lofty-rs#113]
### Summary

The values read from different fields that all map to the same `ItemKey` appear in no particular order.

They don't follow the ordering and precedence defined by the mapping macro. This ordering only affects which field gets written, namely only the first one.

**Comment by Serial-ATA** [comment]
Do you mean, for example, an MP4 file that has both a `----:com.apple.iTunes:BPM` and a `tmpo` atom, they could possibly be stored in the tag in the order [`tmpo`, `----:com.apple.iTunes:BPM`] despite the freeform coming first in the mapping macro?

Items are stored in the order they appear in the file, they shouldn't be expected to appear in any particular order. The ordering only matters in the macro to pick out the key to write, alongside possible keys that we can also read.

If there is a different value that can occur between the keys, they should probably have separate `ItemKey` variants. There should only be multiple keys if you can expect them all to have a similar value, such as in the case of `ItemKey::EncodedBy` for Vorbis Comments: 
https://github.com/Serial-ATA/lofty-rs/blob/f73783aa8af5297d792227078500404f3f297510/src/tag/item.rs#LL336C2-L336C43

**Comment by uklotzde** [comment]
Thanks for the clarification.

`tmpo`/`----:com.apple.iTunes:BPM` is a special case because here you should write into both atoms, but with different values. The generic code should probably only write integer bpms as the least common denominator.

The most awkward case is `TIT1`/`GRP1`, caused by Apple's ignorance and stupidity.

**Comment by Serial-ATA** [comment]
Yet another issue caused by iTunes.

When I first heard about GRP1, I had assumed it was equivalent. I've never worked with these tags myself.

After seeing https://community.mp3tag.de/t/support-for-new-itunes-grouping-id3-frame-grp1/18523/2 though, I think it should have its own `ItemKey::Grouping`.

**Comment by uklotzde** [comment]
> ...I think it should have its own `ItemKey::Grouping`.

Probably `ItemKey::AppleId3Grouping`, as warning in which context this requires special handling and that this `ItemKey` is only used for ID3 tags. Unfortunately, every application then has to deal with it and decide how to handle the Content Group for ID3 tags.

If they had chosen a new tag identifier for the *work name* instead everything would be easy, portable, and backwards compatible. Such a dumb decision, unbelievable.

**Comment by uklotzde** [comment]
I consider this resolved for now. New `ItemKey`s for disambiguation could be introduced on demand when required.
