### ISSUE TITLE
Provide the `tests` dir in the tarball distributed on crates.io

### ISSUE THREAD

**Issue by tenzap** [Serial-ATA/lofty-rs#157]
`tests` dir is not in the tarball distributed on crates.io.

Would you include them? We would need them for automatic package testing inside Debian packages.

BTW, are we allowed to distribute these files?

**Comment by uklotzde** [comment]
IMHO test data should be included in the crates.io package. Unneeded waste of bandwidth and disk space for everyone else.

Why not add this data as a separate artifact to your packaging repo and copy them when needed?

**Comment by tenzap** [comment]
you wrote "should" did you mean "shoudn't" ?

**Comment by uklotzde** [comment]
I only have experience with packing RPMs for Fedora so I cannot comment on your actual use case. But I guess you always have the option to build from source directly from the repo.

If you use crates.io you implicitly rely on the fact that the package has been tested before it has been released.

**Comment by Serial-ATA** [comment]
The tests directory is the reason why I added an explicit `includes` section to Cargo.toml. There are a lot of test assets, with more to come in the future. It really adds up.

Each release is tagged, and there are source downloads from https://github.com/Serial-ATA/lofty-rs/releases if needed.

**Comment by tenzap** [comment]
@uklotzde, in Debian we use the tests from upstream to check that our package actually works with the Debian toolchain (distributed version of rust/cargo and other packages from crates). So your statement `If you use crates.io you implicitly rely on the fact that the package has been tested before it has been released` is not of great help for that scenario.

@Serial-ATA other tools seem to use `excludes` section instead of `includes`.

Unfortunately, using tarball from github doesn't fit the workflow that is in place for rust packages. It was decided to use only packages from crates.io (for various reasons). So we have only 2 options left: Disable test suite or manually add the files from your archive for each new release.

BTW, `hound` seems to distribute its test files in the crates.io package (I didn't check for `TagLib`)

**Comment by uklotzde** [comment]
https://doc.rust-lang.org/cargo/reference/publishing.html#packaging-a-crate

> You may want to check the size of the .crate file to ensure you didn't accidentally package up large assets that are not required to build your package, such as test data, website documentation, or code generation.
