### ISSUE TITLE
APE track/disk numbers are not properly converted when writing

### ISSUE THREAD

**Issue by Serial-ATA** [Serial-ATA/lofty-rs#159]
### Reproducer

I tried this code:

```rust
use lofty::{Accessor, Tag, TagExt, TagType};

fn main() {
    let mut tag = Tag::new(TagType::APE);
    tag.set_track(5);
    tag.set_track_total(15);
    tag.save_to_path("foo.mp3").unwrap();
}
```

### Summary

When using `Tag`, the track/disk numbers are not properly converted when saving to an APE tag. This is identical to #145, as it will be saved as two separate items: `........Track.5........Track.15`.

This issue was fixed for ID3v2 in #149, which stores number pairs in the same format. The fix should be similar, if not identical.

**Comment by uklotzde** [comment]
Common functions and constants should extracted and shared, not duplicated. Maybe also some tests need to be generalized.
