### ISSUE TITLE
Make allocation limit configurable in `ParseOptions`

### ISSUE THREAD

**Issue by Serial-ATA** [Serial-ATA/lofty-rs#208]
### Summary

The default allocation limit of 8MB could potentially not fit every use case, it would be nice to have this be configurable.

### API design

```rust
impl ParseOptions {
    pub fn allocation_limit(&mut self, limit: usize) -> Self;
}
```

**Comment by G2-Games** [comment]
I have run into several files that are larger than this limit, is there a solution for now? 

I can provide a file if needed

**Comment by Serial-ATA** [comment]
There's no way to work around the limit for now.

I am intrigued though, you have files with tags exceeding 8MB? Do you have a bunch of large images or is it something else?

**Comment by G2-Games** [comment]
Yes, I have a few files that I have encountered in my library that have ridiculously large images

**Comment by Serial-ATA** [comment]
Alright, I might be able to get this implemented next week.
