### ISSUE TITLE
feature request: write length to mp3

### ISSUE THREAD

**Issue by tramhao** [Serial-ATA/lofty-rs#21]
Hello and thanks so much for your PR and everything is working. Right now, I can only find a little draw back. When the playlist contains more than 50 songs, it'll take 1-2 seconds to load. I think maybe it comes from the reading of duration, as originally this info is from tag, and only update tag when it's very different from gstreamer result. Is it better to write it to tag? Thanks!

**Comment by Serial-ATA** [comment]
I hadn't even thought of that, that does sound like a good idea. To be clear, you mean you want to do something like:

```rust
// Read with properties
let file = Probe::open(path)?.read(true)?;
let properties = file.properties();

// Assumed to be ID3v2
let tag = file.primary_tag_mut();
tag.store_properties(properties);

...

// Then reread without properties
let file = Probe::open(path)?.read(false);
ket tag = file.primary_tag();
let duration = tag.get_string(ItemKey::Duration);
```

**Comment by Serial-ATA** [comment]
This is also just a speed issue I'll have to address.

**Comment by tramhao** [comment]
Before I was writing code for gomu(https://github.com/issadarkthing/gomu), I found that read from tag is much  faster than getting duration. length is an official tag specification on id3v2. However, for ogg opus flac etc, duration is part of property, so it should be fast enough.

**Comment by tramhao** [comment]
> I hadn't even thought of that, that does sound like a good idea. To be clear, you mean you want to do something like:
> 
> ```rust
> // Read with properties
> let file = Probe::open(path)?.read(true)?;
> let properties = file.properties();
> 
> // Assumed to be ID3v2
> let tag = file.primary_tag_mut();
> tag.store_properties(properties);
> 
> ...
> 
> // Then reread without properties
> let file = Probe::open(path)?.read(false);
> ket tag = file.primary_tag();
> let duration = tag.get_string(ItemKey::Duration);
> ```
> 
> Though the only thing that can be stored from properties is the duration. I don't know how much sense `insert_duration` makes. What do you think?

The logic is all right. The only problem is that it require getting duration so it's time consuming for mp3. I think it's better to trust the length read from id3 tag, and leave the opportunity to update it to correct value. 

I'm also confused for other file types. Seems they don't have this problem and the duration can be retrieved very fast.

**Comment by Serial-ATA** [comment]
> Before I was writing code for gomu(https://github.com/issadarkthing/gomu), I found that read from tag is much faster than getting duration. length is an official tag specification on id3v2. However, for ogg opus flac etc, duration is part of property, so it should be fast enough.

Yeah, `TLEN` exists for both ID3v2 and RIFF INFO. Those are still accessible using `Tag::get_string` with `ItemKey::Unknown(String::from("TLEN"))`.

I think the best thing to do here is add `Probe::read_properties`.

> I'm also confused for other file types. Seems they don't have this problem and the duration can be retrieved very fast.

MP3 is multiple times slower to read than every other format, since we read each frame header. I'll have to come up with a more elegant solution.

**Comment by Serial-ATA** [comment]
https://github.com/Serial-ATA/lofty-rs/commit/af37013e5433f5f2ca09174d89e9230a98d50c7d Significantly improves the speed of MP3 reads. A 6.6MiB file now reads in 32µs instead of 15ms. You should be fine to read properties now. Could you test it out before it gets published?

```rust
let file = Probe::open(path)?.read(true)?;
let properties = file.properties();

let length: Option<u64> = None;

let tag = file.primary_tag().unwrap();

if let Some(len_tag) = tag.get_string(&ItemKey::Length) {
	length = Some(len_tag.parse()?)
}

if length.is_none() {
	length = Some(properties.duration().as_millis());
}
```

**Comment by tramhao** [comment]
Yes, the reading of mp3 is very fast now! no noticeable delay when open the app with playlist of 50 songs.

**Comment by Serial-ATA** [comment]
Thanks!
