### ISSUE TITLE
Ignore Invalid Tag frames instead of erroring in ID3v2

### ISSUE THREAD

**Issue by FriederHannenheim** [Serial-ATA/lofty-rs#211]
I have a few audio files which will work correctly with some other tag readers (id3v2 command line tool and GNOME Tracker3) but don't with lofty. After a bit of debugging with a hex editor I found out that there is additional data after the last frame in the tag where lofty tries to read another frame. When it fails to parse the frame header it panics.

I would like to see this error ignored since the other frames are still valid and useful.

**Comment by Serial-ATA** [comment]
This was recently discussed here: https://github.com/Serial-ATA/lofty-rs/issues/204#issuecomment-1573942708

This is the planned behavior of [ParsingMode::Relaxed](https://docs.rs/lofty/latest/lofty/enum.ParsingMode.html#variant.Relaxed), it just hasn't really been implemented yet.

**Comment by Serial-ATA** [comment]
This has been fixed for a few months now with the introduction of the new default `ParsingMode::BestAttempt`.
