### ISSUE TITLE
multiple lyrics support

### ISSUE THREAD

**Issue by tramhao** [Serial-ATA/lofty-rs#22]
Seems that the implementation of lyrics are totally different. In my app, originally for mp3 file, all lyrics are embeded with language extension and can be switched by `T` key.

However, with the general implementation in lofty, the language extension is missing. Is there a good way to handle it in my app, or lofty? Thanks.

**Comment by tramhao** [comment]
Currently in my master, when saving tag, the lyric is not saved. I added following code but doesn't work:
```rust
            if !self.lyric_frames_is_empty() {
                if let Some(lyric_frames) = self.lyric_frames() {
                    for l in lyric_frames {
                        tag.insert_text(ItemKey::Lyrics, l.text);
                    }
                }
            }
```

**Comment by tramhao** [comment]
I just checked again and the above code works for opus, but not for mp3. I think the problem is because in opus the lyric is only a string, but in mp3 it's a lyric struct as defined in id3v2.

**Comment by tramhao** [comment]
And the save photo code is not working as well:
```rust
            // if let Some(any_picture) = self.picture().cloned() {
            if let Some(front_cover) = tag.get_picture_type(PictureType::CoverFront).cloned() {
                tag.push_picture(front_cover);
            }


```
I tried the commented version also but not working.

**Comment by tramhao** [comment]
> And the save photo code is not working as well:
> 
> ```rust
>             // if let Some(any_picture) = self.picture().cloned() {
>             if let Some(front_cover) = tag.get_picture_type(PictureType::CoverFront).cloned() {
>                 tag.push_picture(front_cover);
>             }
> ```
> 
> I tried the commented version also but not working.

Checked again, seems mp3 is not working, flac is ok, but with many error(a large amount of data etc).

**Comment by tramhao** [comment]
Code is in dev branch of termusic, please kindly help.

**Comment by Serial-ATA** [comment]
> Seems that the implementation of lyrics are totally different. In my app, originally for mp3 file, all lyrics are embeded with language extension and can be switched by `T` key.
> 
> However, with the general implementation in lofty, the language extension is missing. Is there a good way to handle it in my app, or lofty? Thanks.

Since ID3v2 is the only format that does anything language specific, you'd have to use an `Id3v2Tag` and get all of the `USLT` frames.

In your case, you'd have to read an `Mp3File`, rather than use `Probe`.

```rust
let file = Mp3File::read_from(&mut file, false)?;

if let Some(id3v2_tag) = file.id3v2_tag() {
    for lyrics_frame in id3v2_tag.iter().filter(|f| f.id_str() == "USLT") {
        if let FrameValue::UnSyncText(info) = lyrics_frame.content() {
            let lang = info.language;
            ...
        }
    }
}
```

I hadn't thought about making methods for these. I'll add `Id3v2Tag::{lyrics,comments}` to make this more convenient.

**Comment by Serial-ATA** [comment]
And could you make a new issue for the pictures? :)

**Comment by tramhao** [comment]
yes, sure. Please check https://github.com/Serial-ATA/lofty-rs/issues/23

**Comment by Serial-ATA** [comment]
Did the code above work for you?

**Comment by Serial-ATA** [comment]
I added `Id3v2Tag::{unsynch_text, comments}` in https://github.com/Serial-ATA/lofty-rs/commit/b805af3a0c13699b6da20de5cb41fb8a220f907c. You can now do this:

```rust
let file = Mp3File::read_from(&mut file, false)?;

if let Some(id3v2_tag) = file.id3v2_tag() {
    for lyrics_frame in id3v2_tag.unsync_text() {
        let lang = info.language;
    }
}
```

**Comment by tramhao** [comment]
Yes, reading multiple lyrics for mp3 is working now. I'll figure out the writing accordingly. Thanks so mcuh!

**Comment by Serial-ATA** [comment]
Thanks!
