### ISSUE TITLE
Issue saving picture

### ISSUE THREAD

**Issue by tramhao** [Serial-ATA/lofty-rs#23]
And the save photo code is not working as well:

```rust
            // if let Some(any_picture) = self.picture().cloned() {
            if let Some(front_cover) = tag.get_picture_type(PictureType::CoverFront).cloned() {
                tag.push_picture(front_cover);
            }
```
I tried the commented version also but not working.  seems mp3 is not working, flac is ok, but with many error(a large amount of data etc).

**Comment by Serial-ATA** [comment]
Which part isn't working? `get_picture_type`, `push_picture`, or `save_to`?

**Comment by Serial-ATA** [comment]
And for FLAC, do you mean you get `LoftyError::TooMuchData`? Because FLAC does have different size requirements than every other format.

**Comment by tramhao** [comment]
Yes it's LoftyError::TooMuchData, but when I embed the photo to another format, and found the photo is not big, 300x300, jpeg file.
Maybe the file mimetype is wrong?
![image](https://user-images.githubusercontent.com/7751505/147717475-5a3cb71d-5f16-4779-8dc6-39e22b4cad92.png)

**Comment by tramhao** [comment]
I mean the file is actually png, but the mimetype is jpeg, and this could lead to TooMuchData error?

**Comment by Serial-ATA** [comment]
Oops, nope I got a number wrong somewhere. However for the mimetype, while Lofty doesn't depend on it being correct, you should be writing the correct mimetype, so other apps don't misinterpret it.

**Comment by Serial-ATA** [comment]
The `TooMuchData` error was fixed. What issues were you having with MP3?

**Comment by tramhao** [comment]
Maybe because I didn't check file format when downloading them....
Previously when I write these codes, the image downloaded from server are all jpeg. Now there are more and more png.
        Ok(Picture::new_unchecked(
            PictureType::Other,
            MimeType::Jpeg,
            Some(String::from("Image")),
            encoded_image_bytes,
        ))
Let me switch back to lofty for writing then check again.

**Comment by Serial-ATA** [comment]
If the format is unknown, you can always use [Picture::from_reader](https://docs.rs/lofty/latest/lofty/struct.Picture.html#method.from_reader). For the code you posted above, you are looking for a `PictureType::CoverFront`, but you're creating a `PictureType::Other`.

**Comment by tramhao** [comment]
Right now the photo is written for flac and no errors. I found some other bugs and will report in a new issue. Thanks.
