### ISSUE TITLE
Write lyric for id3 fails if not using id3tag

### ISSUE THREAD

**Issue by tramhao** [Serial-ATA/lofty-rs#25]
If using lofty::tag::new(tag_type), write lyric will fail for mp3 and wav file format, but read lyric works.

if using id3v2tag::default(), write lyric works with below code. Read works too.
```rust
             if !self.lyric_frames_is_empty() {
                        if let Some(lyric_frames) = self.lyric_frames() {
                            for l in lyric_frames {
                                if let Ok(l_frame) = Frame::new(
                                    "USLT",
                                    FrameValue::UnSyncText(LanguageFrame {
                                        encoding: TextEncoding::UTF8,
                                        language: l.lang,
                                        description: l.description,
                                        content: l.text,
                                    }),
                                    FrameFlags::default(),
                                ) {
                                    tag.insert(l_frame);
                                }
                            }
                        }
                    }


```

I checked the written tag, and the lyric field is red in kid3, without content, with language = '[1'

**Comment by Serial-ATA** [comment]
Ah, I didn't special case USLT when converting `Tag` -> `Id3v2Tag`. Also, just a heads up since I know you rely on languages, you should read [this](https://docs.rs/lofty/latest/lofty/id3/v2/struct.Id3v2Tag.html#from-tag) to see how its supposed to handle conversions. I'll fix it so it actually behaves that way though :)

**Comment by tramhao** [comment]
No hurry, as I'm right now using separate code for handling mp3/wav with id3v2Tag, so there is no conversion needed.

**Comment by Serial-ATA** [comment]
https://github.com/Serial-ATA/lofty-rs/commit/d312f48406d770949e7f99c04304b945317786a1 Hopefully fixed it. Could you test it out?

**Comment by tramhao** [comment]
Yes， the lyric is written without problem now.
