### ISSUE TITLE
ParseOptions: Add `read_tags`

### ISSUE THREAD

**Issue by Serial-ATA** [Serial-ATA/lofty-rs#251]
### Summary

Unexpectedly, many projects pull in Lofty *solely* for its property reading. Each time it is used for this purpose, however, all of the tags are still being parsed unnecessarily.

Just as one can skip property reading with `ParseOptions::read_properties(false)`, it may be worth adding `ParseOptions::read_tags()`.

### API design

```rust
impl ParseOptions {
    pub fn read_tags(&mut self, read_tags: bool) -> Self;
}
```

**Comment by vincehi** [comment]
hello, it would be great to be able to do `ParseOptions::read_tags()`. Or wouldn't we have to use a [features] for this? Because in my case I wouldn't need the tags at all.

**Comment by Serial-ATA** [comment]
@vincehi Hello!

There wouldn't need to be a feature for this. Since `read_properties` already exists, this would act the same. When parsing, the tags will just be skipped and stored as their defaults (`Id3v2Tag::default()`, etc.).

**Comment by vincehi** [comment]
Does this seem complicated to you? I preferred to use taglib even though it also analyses tags even though I don't need it, but it doesn't crash on the file format (UTF-...). On the other hand, the length recovered is in milisecond on lofty, which is very convenient for me.

**Comment by Serial-ATA** [comment]
> Does this seem complicated to you?
No, it'd be a pretty quick feature to add. I just haven't bothered since I've been working on more requested features.

> it doesn't crash on the file format (UTF-...).

Can you make issues for any crashes you have with Lofty? There haven't been any text encoding issues that I'm aware of.

**Comment by vincehi** [comment]
I think I had the same problem as this person https://github.com/Serial-ATA/lofty-rs/issues/373. But if I understand correctly, it's on the read tags, not on the read properties. So if in future I could bypass the read tags that would be great.

**Comment by Serial-ATA** [comment]
Yeah, this would avoid the error in #373 entirely. I'll see about getting this in 0.21.0.

**Comment by vincehi** [comment]
Thank's for this option, it's realy fast 🚀
https://github.com/vincehi/pulp/releases
