### ISSUE TITLE
Unable to read metadata from FLAC files with large embedded artwork

### ISSUE THREAD

**Issue by sublipri** [Serial-ATA/lofty-rs#266]
### Summary

FLAC files with large (~8MB+) embedded artwork cause lofty to fail with a TooMuchData error.

### Expected behavior

Lofty should at least still parse the vorbis comments. For my current use case skipping any oversized artwork would be fine, although it might be nice to handle large artwork so that an application could alert users and give them the option to remove it.

**Comment by Serial-ATA** [comment]
Hello!

This exact same situation was being discussed in #208. Would you happen to know how big the pictures are? I may just end up increasing the default allocation limit alongside making it configurable.

**Comment by sublipri** [comment]
Oh, sorry - I didn't notice that when I searched. The largest picture I've encountered was 14.2MB. I also just noticed a file with 12MB of padding that triggers the same error.  Thanks a lot for all your work on the library BTW!  Trying to learn Rust by writing a music manager and lofty seems like the best option for metadata.

Looking with metaflac I noticed that the METADATA blocks specify their length. Would it be possible to use that to allocate extra memory when necessary?

**Comment by Serial-ATA** [comment]
> Looking with metaflac I noticed that the METADATA blocks specify their length. 

We do use the lengths specified. The problem is we can never really *trust* user input. We have to put additional guardrails in place, one of them being the allocation limit, in order to prevent OOM errors.

We used to blindly trust user input, but that doesn't work out anymore given the crate's scale. We have to make sure we don't let in malicious/broken files.

**Comment by sublipri** [comment]
Makes sense. Thanks for the quick reply! A configurable allocation limit sounds good then. I'll close this in favor of the other issue.

**Comment by Serial-ATA** [comment]
> The largest picture I've encountered was 14.2MB. I also just noticed a file with 12MB of padding that triggers the same error.

Forgot to mention, I feel like 16MB as the default would prevent issues like this in the future. I'll likely bump it up to that when I get around to making it configurable.

**Comment by sublipri** [comment]
16MB sounds like a good default to me!
