### ISSUE TITLE
Error: An abnormally large amount of data was provided, and an overflow occurred

### ISSUE THREAD

**Issue by probablykasper** [Serial-ATA/lofty-rs#274]
### Reproducer

Add a 9MB+ cover to a `.opus` file, and open it like this:

```rust
let probe = match lofty::Probe::open(path) {
  Ok(f) => {
    let parse_options = lofty::ParseOptions::new()
      .read_properties(false)
      .parsing_mode(lofty::ParsingMode::Strict);
    f.options(parse_options)
  }
  Err(e) => panic!("File does not exist: {}", e),
};

let mut tagged_file = match probe.read() {
  Ok(f) => f,
  Err(e) => panic!("Unable to read file: {}", e), // <-- this panics
};
```

### Summary

I used lofty to add a 9MB jpg artwork to an `.opus` file and saving it. When reading it again, I get this error from `probe.read()`:
> An abnormally large amount of data was provided, and an overflow occurred

### Expected behavior

No error

### Assets

[Original file (probe works with this one).opus.zip](https://github.com/Serial-ATA/lofty-rs/files/13059862/Original.file.probe.works.with.this.one.opus.zip)
[New cover that was added to the new file.jpg.zip](https://github.com/Serial-ATA/lofty-rs/files/13059864/New.cover.that.was.added.to.the.new.file.jpg.zip)
[New file (causes probe error).opus.zip](https://github.com/Serial-ATA/lofty-rs/files/13059865/New.file.causes.probe.error.opus.zip)

**Comment by Serial-ATA** [comment]
The message for `ErrorKind::TooMuchData` wasn't updated when it was reused for the allocation limit, so it's pretty misleading. :smile:

The allocation limit (currently 8MB) will be raised to 16MB as discussed in #266, and will be configurable in the future with #208.

**Comment by probablykasper** [comment]
Ah, I see. How come you can write >8MB but not read it though?

**Comment by Serial-ATA** [comment]
Yeah, that's definitely an issue. I just simply hadn't thought of that situation, having never encountered items >8MB in my library or in the wild.

`Picture`s are one of the cases where we don't do the full allocation upfront, it just grows as it's being written to. That could definitely be improved to take the limit into account.

Given the number of reports for this, tomorrow I'll try looking into making this configurable and larger by default.
