### ISSUE TITLE
IDv3 Text decoding: UTF-16 string has an invalid byte order mark

### ISSUE THREAD

**Issue by huanie** [Serial-ATA/lofty-rs#306]
### Reproducer

I tried this code where path is just an mp3 file:

```rust
read_from_path(&path)
```

### Summary

I hope the provided text file is enough to identify the problem. The text file is the beginning of the mp3 file I tried to read from. 

### Assets

[tags.txt](https://github.com/Serial-ATA/lofty-rs/files/13760315/tags.txt)

**Comment by Serial-ATA** [comment]
Hello, thanks for the report.

Could you reupload the asset as a binary file? Data is lost in the conversion to text.

**Comment by huanie** [comment]
[Uploading tags…]()
