### ISSUE TITLE
Improper use of PascalCase/UpperCamelCase in the ItemKey enum.

### ISSUE THREAD

**Issue by Hellrespawn** [Serial-ATA/lofty-rs#327]
### Summary

`PodcastURL` has `URL` fully uppercase, where all other instances of the word use `Url`. Similarly, `PodcastGlobalUniqueID` has `ID` fully uppercase where all other instances use `Id`.

**Comment by uklotzde** [comment]
Just fix it and open a PR. I guess @Serial-ATA is happy to merge these fixes. We have already introduced breaking changes, see #329.

**Comment by uklotzde** [comment]
Related: #107.

**Comment by Serial-ATA** [comment]
Yeah, I have no problem changing the variants. I'm just not a place where I can make those changes right now. It'd have to wait a few days unless a PR is made between then.

**Comment by uklotzde** [comment]
Done: #332.
