### ISSUE TITLE
Picture not saved to MP3 file

### ISSUE THREAD

**Issue by bmreading** [Serial-ATA/lofty-rs#36]
I tried this code:

```rust
use lofty::{MimeType, Picture, PictureType, Tag, TagExt, TagType};
use std::path::Path;

fn main() {
    let picture_data = std::fs::read(Path::new("picture.jpg")).unwrap();

    let picture = Picture::new_unchecked(
        PictureType::CoverFront,
        MimeType::Jpeg,
        Some(String::from("cover")),
        picture_data,
    );

    let mut tag = Tag::new(TagType::Id3v2);
    tag.push_picture(picture);
    tag.save_to_path(Path::new("file.mp3")).unwrap();
}
```

**Describe the bug**
When saving a tag to an MP3 using v0.5.1, the picture is not saved. Debugger does show tag actually has valid picture, but operation isn't being performed. Other tag items work okay. I've also tested a FLAC file, and that worked fine for saving pictures.

**Expected behavior**
Picture in tag is saved to file.

**Comment by Serial-ATA** [comment]
Thanks! I somehow missed that. It should be fixed in https://github.com/Serial-ATA/lofty-rs/commit/689e5fb28b43ba60fd6d389d357a6a5bfe866631, could you test it out?

**Comment by bmreading** [comment]
Thanks for working on this. I tested out by swapping in the current main branch (`cargo.toml` has `lofty = { git = "https://github.com/Serial-ATA/lofty-rs.git" }`), but unfortunately, I get the same result.

**Comment by Serial-ATA** [comment]
I tried your code above and it works. Can you try `cargo update`?

**Comment by bmreading** [comment]
I apologize. I was checking for update from my file browser, and it looks like it wasn't reflecting the current file's metadata. I checked again using another method, and definitely see it working. It seems the bug is squashed. Thanks again for your help. Closing this now.
