### ISSUE TITLE
Wav: Failed to read RIFF INFO item value

### ISSUE THREAD

**Issue by Ferry-200** [Serial-ATA/lofty-rs#373]
### Reproducer

I tried this code:

```rust 
let tagged_file: Option<TaggedFile> = match lofty::read_from_path(
        "C:\\Users\\ferry\\Music\\test\\大哉乾元(洛天依人声版)_MMM.wav",
    ) {
        Ok(value) => Some(value),
        Err(err) => {
            // Wav: Failed to read RIFF INFO item value
            println!("{}", err);
            None
        }
    };
```

The lofty version is "0.18.2" 
![image](https://github.com/Serial-ATA/lofty-rs/assets/98510207/9b3a1258-0619-4fbf-8234-98c4dd2d0ea7)

### Summary

There is an error "Wav: Failed to read RIFF INFO item value" 

The Windows Properties page can read the tags in it. I can also play it on Windows Media Player.

Can anyone provide some information about this? Thanks.

### Expected behavior

Read tag correctly.

### Assets

[大哉乾元(洛天依人声版)_MMM.wav](https://drive.google.com/file/d/1IT-5HYwHYHkAPs7H4Wp98T-_aZsL5D4E/view?usp=sharing)

**Comment by Serial-ATA** [comment]
Hello!

Your file has items that are not UTF-8 encoded. What is your local character encoding? If Windows is able to read it, that means the file is using your system encoding.

**Comment by Ferry-200** [comment]
UTF-16.
And the file's title, artist, ... tag are UTF-16 LE encoded.

**Comment by Serial-ATA** [comment]
Hm. It's unfortunate that RIFF doesn't specify a text encoding. We would be able to *somewhat* reliably detect UTF-16 LE, but there's no BOM either. The only way for us to know ahead of time how to decode the text would be using [GetACP()](https://learn.microsoft.com/en-us/windows/win32/api/winnls/nf-winnls-getacp) from Windows. Don't know how I feel about having platform-specific code in Lofty, though.

**Comment by Ferry-200** [comment]
Maybe we can simply set the way to decode text when read riff info. Obviously it is not a good way to fix it though.

**Comment by Serial-ATA** [comment]
That would also work. Gonna have to think about this one. For now I'd just recommend changing the encoding of your files to UTF-8, that's what most libraries (outside of TagLib) will exclusively support.

**Comment by aMytho** [comment]
Being able to use alternate encodings would be nice. In my project I need to build an index of all tag data (title/artist/genre/etc). I'm guessing these files are in UTF16 so I'm having the same issue.

They are able to be read in KDE Elisa. I think that project uses taglib though.

**Comment by Serial-ATA** [comment]
> They are able to be read in KDE Elisa. I think that project uses taglib though.

Do your files have other tags? In the case of the file provided in this issue, it has both a RIFF INFO and an ID3v2 tag. Elisa ends up just using the data from the ID3v2 tag and logs UTF-8 errors for the RIFF INFO tag.

**Comment by aMytho** [comment]
I added metadata to several .wav files with musicbrainz picard.  I think picard adds ID3v2 tags and RIFF Info tags to wavs by default. How would I check the tag types?

Running `ffprobe` against it shows the metadata with a warning simlar to: `[json @ 0x5664cd0010c0] 1 invalid UTF-8 sequence(s) found in string 'Example�s', replaced with '�'`. The missing character should be an apostrophe.

I have another file with the ellipses character. It also fails in lofty. No errors in ffprobe or elisa.

I have other files with non-english characters. They play in Elisa and I can view the metadata correctly there. When I pass the files into lofty, I get the following error: `FileDecoding(Wav: "Failed to read RIFF INFO item value")`

**Comment by Serial-ATA** [comment]
>  I think picard adds ID3v2 tags and RIFF Info tags to wavs by default.

That's probably it. Most serious music players will check all tags to fill in any missing fields. Trying to load a non UTF-8 RIFF INFO tag with Elisa will log errors, and it will fallback to the info it can get from the ID3v2 tag. Elisa just depends on `KFileMetaData` which uses TagLib, and as far as I can tell they don't set a `StringHandler`.

I will say, a hard error shouldn't be the case outside of `ParsingMode::Strict`. That's something I can fix (just ignore it and log a warning, like TagLib).

> How would I check the tag types?

I use [kid3](https://kid3.kde.org/) to see what tags a file has. It uses TagLib, and with the asset provided in the issue, it ignores any field in the RIFF INFO tag that it can't parse as UTF-8.

**Comment by aMytho** [comment]
I downloaded the kid3 program. The files that failed to read in lofy had an ID3 **and** a RIFF tag. Some also had extra tags, but it didn't list a type or any info. 

I noticed some files display the data correctly in the ID3 tag, but show an empty entry in the RIFF tag. For example, the file with the invalid UTF8 warning when inspected with ffprobe had an apostrophe in the title. It is visible in the ID3 tag, but the RIFF tag shows the title as empty (key exists, no value). Other values were replaced instead. ID3 has a - (dash) in the artist entry while RIFF has a ? (question mark).

**Comment by Serial-ATA** [comment]
> Some also had extra tags, but it didn't list a type or any info.

Kid3 puts markers to show that you can add another tag to the file, not necessarily that it's present, BTW.

> It is visible in the ID3 tag, but the RIFF tag shows the title as empty (key exists, no value).

Yeah, I haven't actually seen anyone make use of TagLib's `StringHandler`. I imagine in most cases no errors are noticed since Picard (and likely other tools) add an ID3v2 tag for compatibility. The real issue here is that in Lofty it's a hard error, rather than a discard & warn.

**Comment by Ferry-200** [comment]
From above, I think in the future, `ParsingMode::Strict = false` will cause `read_from` to log Err instead of returning Err when encountering a tag that cannot be parsed correctly. If at least one tag is parsed properly, read_from will still return OK. Otherwise, the Err will be returned.

**Comment by aMytho** [comment]
> Kid3 puts markers to show that you can add another tag to the file, not necessarily that it's present, BTW.

Interesting! I've never heard of this app, but I think it will be helpful for my project. I was using picard to inspect metadata but this one seems better for what I need.
