### ISSUE TITLE
M4A support

### ISSUE THREAD

**Issue by musaoruc** [Serial-ATA/lofty-rs#38]
Adding .m4a support would have been nice since that format is quite popular.

**Comment by Serial-ATA** [comment]
Hello! Lofty already supports M4A, and really any other MP4 container format :). Are you having trouble reading these files?

**Comment by musaoruc** [comment]
Not me personally but this project does https://gitlab.gnome.org/ebassi/amberol/-/issues/22

**Comment by Serial-ATA** [comment]
Ah, that project is using an outdated version. I recently made many fixes for MP4. Could you inform the maintainer of that project?

**Comment by musaoruc** [comment]
Thanks for the quick responses! Really appreciated. I will try to inform them.

**Comment by Serial-ATA** [comment]
I'll close this, as it should be resolved. Please do make a bug report if it remains a problem! :)
