### ISSUE TITLE
Issues with ID3v2 TRCK count/total separation

### ISSUE THREAD

**Issue by basharovV** [Serial-ATA/lofty-rs#417]
### Reproducer

I tried this code:

```rust
fn write_track_number() {
    let mut tag = lofty::tag::Tag::new(TagType::Id3v2);
    tag.insert(TagItem::new(
        ItemKey::from_key(TagType::Id3v2, "TRCK"),
        ItemValue::Text(String::from("1")),
    ));

    println!("{:?}", tag.track()); // None
    println!("{:?}\n", tag.track_total()); // Some(1)

    tag.insert(TagItem::new(
        ItemKey::from_key(TagType::Id3v2, "TRCK"),
        ItemValue::Text(String::from("1/14")),
    ));

    println!("{:?}", tag.track()); // None
    println!("{:?}\n", tag.track_total()); // None

    tag.save_to_path("src/blank.mp3", WriteOptions::new());

    let mp3_file = read_from_path("src/blank.mp3").unwrap();

    for tag_item in mp3_file.tags() {
        for tag in tag_item.items() {
            println!("Found tag: {:?}", tag); // Value is "0/1/14"?
        }
    }
}
```

Output:
```
None
Some(1)

None
None

Found tag: TagItem { lang: [88, 88, 88], description: "", item_key: TrackTotal, item_value: Text("0/1/14") }
```

### Summary

I'm not sure if I'm doing this wrong, but when writing the TRCK tag, I'm seeing some strange behaviour:
- `tag.track()` is `None` and `tag.track_total()` is `Some(1)` when TRCK is a single number. Shouldn't this be the other way round? 
- `tag.track()` and `tag.track_total()` are `None` when providing a delimited TRCK like "1/14"
- A "0/" is prefixed when saving the tag to a file, so the resulting tag looks like "0/1/14" instead of "1/14" (or "0/1" instead of just "1")

**Comment by Serial-ATA** [comment]
Hello!

`ItemKey::from_key` is confusing and really only used internally. I might make it `doc(hidden)` or at least document it better.

So, `ItemKey` doesn't retain any format-specific keys. You should be using `ItemKey::TrackTotal` and `ItemKey::TrackNumber` individually. They will map appropriately when writing the tag.

**Comment by basharovV** [comment]
Ah, thank you for the clarification, I expected lofty to handle the separation here. `ItemKey::from_key` is still useful to me though because I already have a dict of the exact ID3v2/Vorbis tags to write, so I thought I could use this function to map without having to do additional format-specific handling. Or is there a better way to handle my use case?

**Comment by Serial-ATA** [comment]
`Tag` is intended to be format-agnostic, so you should never have to worry about any format-specific handling. If you have to read/write items that `ItemKey` doesn't cover then you should use [Id3v2Tag](https://docs.rs/lofty/latest/lofty/id3/v2/struct.Id3v2Tag.html) and [VorbisComments](https://docs.rs/lofty/latest/lofty/ogg/struct.VorbisComments.html) (and any other concrete format that you have specific keys for). Both can be split ([SplitTag](https://docs.rs/lofty/latest/lofty/tag/trait.SplitTag.html)) into a `Tag` and merged back ([MergeTag](https://docs.rs/lofty/latest/lofty/tag/trait.MergeTag.html)) into their concrete type

**Comment by basharovV** [comment]
Makes sense! I'll close this issue then. Thanks for this library!
