### ISSUE TITLE
Amberol crash related to lofty attempt to divide by zero

### ISSUE THREAD

**Issue by azarok** [Serial-ATA/lofty-rs#42]
Amberol is using lofty to extract the metadata from song files, and it crashed when the music folder was selected during the installation.
Please find the error.

thread 'main' panicked at 'attempt to divide by zero', /run/build/amberol/vendor/lofty/src/mp3/properties.rs:130:42

Opened issue on Amberol git page
https://gitlab.gnome.org/World/amberol/-/issues/80

Thank you

**Comment by Serial-ATA** [comment]
Thanks! I see where it's failing. Could you provide an asset that causes the panic? I'd like to see how others handle this situation to keep the data accurate.

**Comment by Serial-ATA** [comment]
Fixed in https://github.com/Serial-ATA/lofty-rs/commit/b1ef1f7adc4dfda84337ee7e9b2b00c6c980bc00 :). Just a word of warning, that file is corrupted. FFmpeg produces multiple warnings when reading it.
