### ISSUE TITLE
Support for `total_samples` property

### ISSUE THREAD

**Issue by qarmin** [Serial-ATA/lofty-rs#45]
Somehow Strawberry/Clementine/FFprobe is able to print length of music, even if in tags there is no such information.

When looking at `metaflac` output I saw that length of music can be guessed by dividing total samples with sample rate (e.g. - 7609896 / 44100 = 172,56s => 2 min 53 s)

Currently I don't see now total samples property in lofty code, so I can't guess audio length(maybe there is different/better approach to do this, but I don't know any)

**Comment by Serial-ATA** [comment]
When the total sample count is available it's already used to guess the duration. What types of files are giving you the wrong durations? I know some have better fallback methods than others.

**Comment by qarmin** [comment]
Example files(mp3, flac, ogg, m4a):
[07-Lovefool.zip](https://github.com/Serial-ATA/lofty-rs/files/8602398/07-Lovefool.zip)
[House In a Forest Loop.zip](https://github.com/Serial-ATA/lofty-rs/files/8602400/House.In.a.Forest.Loop.zip)
[Jerzy Rzymowski, Prestiż.zip](https://github.com/Serial-ATA/lofty-rs/files/8602402/Jerzy.Rzymowski.Prestiz.zip)
[Muzyka.zip](https://github.com/Serial-ATA/lofty-rs/files/8602404/Muzyka.zip)
[Portal2.zip](https://github.com/Serial-ATA/lofty-rs/files/8602405/Portal2.zip)

**Comment by Serial-ATA** [comment]
I tested all of those files and the duration is the same as FFmpeg reports. Are you trying to get the duration from the `FileProperties` or the tag? `ItemKey::Length` only exists for ID3v2 and RIFF INFO. I wouldn't rely on that always being available.

**Comment by qarmin** [comment]
My bad, I checked only for length on tags because I only searched for length properties, not duration.

But still I have some more files that doesn't have length and bitrate(mostly wav files)
[grand_beats_110.ogg.zip](https://github.com/Serial-ATA/lofty-rs/files/8608662/grand_beats_110.ogg.zip)
[Player_Jetpack.wav.zip](https://github.com/Serial-ATA/lofty-rs/files/8608669/Player_Jetpack.wav.zip)
[sample.mp3.zip](https://github.com/Serial-ATA/lofty-rs/files/8608679/sample.mp3.zip)
[Wypowied¼_prezesa_UOKiK_Marka_Niechcia³a_o_decyzji_wobec_GetBack.mp3.zip](https://github.com/Serial-ATA/lofty-rs/files/8608684/Wypowied._prezesa_UOKiK_Marka_Niechcia.a_o_decyzji_wobec_GetBack.mp3.zip)
[audacity24bit_level5.flac.zip](https://github.com/Serial-ATA/lofty-rs/files/8608685/audacity24bit_level5.flac.zip)




Broken mp3 file, not sure if calculating bitrate/length is possible
[11 - Make It Holy.mp3.zip](https://github.com/Serial-ATA/lofty-rs/files/8608675/11.-.Make.It.Holy.mp3.zip)

**Comment by Serial-ATA** [comment]
These files work (Same durations and bitrates as FFmpeg):
Wypowied¼_prezesa_UOKiK_Marka_Niechcia³a_o_decyzji_wobec_GetBack.mp3
Player_Jetpack.wav
11 - Make It Holy.mp3
audacity24bit_level5.flac

These ones don't work:
grand_beats_110.ogg (Vendor string isn't UTF8 encoded)
sample.mp3 (Has a zero sized ID3v2 tag)

The two broken ones are actually bugs, but the durations for the others are all fine. Are you using the latest version?

**Comment by qarmin** [comment]
When creating minimal version with the latest git version, I found that problem were caused by using `primary_tag` function.
I expected that if file have no primary tag, then it don't have any tags, but looks that this is not true for files from above. 

Now I see 7 files on my OS that don't have length/bitrate - 6 files with ogg extension, and one from this repository `issue_39.mp3` - ffprobe also doesn't provide info about length/bitrate

**Comment by Serial-ATA** [comment]
Yeah, `issue_39.mp3` has no MPEG frames, so it shouldn't have any properties. Those OGG files could have the same issue as the other ones you sent, with the non UTF-8 vendor strings. That's an issue I'll have to look into.

**Comment by Serial-ATA** [comment]
I think I fixed the issue with the Vorbis files. Could you try out https://github.com/Serial-ATA/lofty-rs/commit/38de51f47dc26773f0b5e22cee4c9c900edbfaab?

**Comment by qarmin** [comment]
Yes, they works now, thanks.

Looks that for now I don't have any files, except broken ones so I don't think that exposing `total_samples` is needed anymore, so I'm closing issue.
