### ISSUE TITLE
Trying to read properties of flac, cause crash `thread 'main' panicked at 'attempt to divide by zero`

### ISSUE THREAD

**Issue by qarmin** [Serial-ATA/lofty-rs#46]
Trying to read properties via `lofty::probe::read_from_path`, cause this crash
```
thread 'main' panicked at 'attempt to divide by zero', /home/rafal/.cargo/git/checkouts/lofty-rs-f5e48f8219b271cf/2266473/src/flac/properties.rs:46:18
```
https://github.com/Serial-ATA/lofty-rs/blob/22664734cfcba7e08db15d7f36b11deea330d3c6/src/flac/properties.rs#L46

[short.flac.zip](https://github.com/Serial-ATA/lofty-rs/files/8617959/short.flac.zip)

**Comment by Serial-ATA** [comment]
Thanks! Fixed in https://github.com/Serial-ATA/lofty-rs/commit/77eec778975b050cdde647a2bf0011ab929fee86
