### ISSUE TITLE
mp3 invalid timestamp

### ISSUE THREAD

**Issue by cryosx** [Serial-ATA/lofty-rs#466]
### Summary

error i get is "Encountered an invalid timestamp: Expected a separator" on mp3 file, flac version works fine.

this is when i call read_from_path

version 0.20.1 works fine

**Comment by Serial-ATA** [comment]
Hello!

That may be fixed already, could you try with the git version? If not, could you email the asset to serial AT [domain on my profile]?

**Comment by cryosx** [comment]
Git version works

**Comment by Serial-ATA** [comment]
Alright, 0.22.0 is currently blocked on #218. It'll probably be a little while before I get that merged. You may need to depend on the git version for now.
