### ISSUE TITLE
GOG soundtracks tags are not properly parsed

### ISSUE THREAD

**Issue by qarmin** [Serial-ATA/lofty-rs#47]
When  trying to read tags from file from below, this errors are printed
```
ID3v2: Failed to parse a frame ID
failed to fill whole buffer
Text decoding: Unable to decode language string
```
FFprobe properly read tags, only with one file it printed `Estimating duration from bitrate, this may be inaccurate`
~~[ 51 - Beorunna's Well.mp3.zip](https://github.com/Serial-ATA/lofty-rs/files/8635445/51.-.Beorunna.s.Well.mp3.zip)~~
~~[10 - Nocturne In Blue.mp3.zip](https://github.com/Serial-ATA/lofty-rs/files/8635448/10.-.Nocturne.In.Blue.mp3.zip)~~
[King of Dragon Pass - 22 - Quite An Adventure.mp3.zip](https://github.com/Serial-ATA/lofty-rs/files/8635450/King.of.Dragon.Pass.-.22.-.Quite.An.Adventure.mp3.zip)
~~[MDK (Tommy Tallarico Studios) - 07 Grenich time.mp3.zip](https://github.com/Serial-ATA/lofty-rs/files/8635452/MDK.Tommy.Tallarico.Studios.-.07.Grenich.time.mp3.zip)~~
~~[MDK (Tommy Tallarico Studios) - 16 Crossfire.mp3.zip](https://github.com/Serial-ATA/lofty-rs/files/8635453/MDK.Tommy.Tallarico.Studios.-.16.Crossfire.mp3.zip)~~

**Comment by Serial-ATA** [comment]
`51 - Beorunna's Well.mp3` was fixed in https://github.com/Serial-ATA/lofty-rs/commit/d52076ea9ab6857aea2776039561b0218ff0b49e. The others are pretty broken, I'll have to look into it more.

**Comment by Serial-ATA** [comment]
`10 - Nocturne In Blue.mp3` was fixed in https://github.com/Serial-ATA/lofty-rs/commit/fe0462bf8ad0dfce3db1b40f655130466c5f46a2.

**Comment by Serial-ATA** [comment]
`MDK (Tommy Tallarico Studios) - 07 Grenich time.mp3` / `MDK (Tommy Tallarico Studios) - 16 Crossfire.mp3` fixed in https://github.com/Serial-ATA/lofty-rs/commit/fc6b145093bb904aa3550bd040d3f16612002530

**Comment by Serial-ATA** [comment]
@qarmin I'm not sure `King of Dragon Pass - 22 - Quite An Adventure.mp3` can be fixed. It has *lots* of issues that can't reasonably be fixed (such as frame sizes that are completely off, missing null terminators, etc).

**Comment by qarmin** [comment]
Probably most GOG soundtracks files comes directly from developers, so they could use very different, old and probably broken apps to save metadata to files, so I think that is expected that some files doesn't have proper tags.

I have some more files, but some may be also broken
[008_Star_Force_tom_6.mp3.zip](https://github.com/Serial-ATA/lofty-rs/files/8645697/008_Star_Force_tom_6.mp3.zip)
[06.mp3.zip](https://github.com/Serial-ATA/lofty-rs/files/8645698/06.mp3.zip)
[07 Rewizja.mp3.zip](https://github.com/Serial-ATA/lofty-rs/files/8645699/07.Rewizja.mp3.zip)
https://www.easypaste.org/file/BJ6HiXLb/02.ogg?lang=en

**Comment by qarmin** [comment]
Looks that also oga files are not supported, or at least this one - [3.oga.zip](https://github.com/Serial-ATA/lofty-rs/files/8646416/3.oga.zip)

**Comment by Serial-ATA** [comment]
oga is supported, you have to use `read_from` instead of `read_from_path` since it could contain multiple different formats.

**Comment by Serial-ATA** [comment]
`06.mp3` fixed in https://github.com/Serial-ATA/lofty-rs/commit/d8ede0e60b7ee8fd60a6f2193c5d09ee2c7c066e.

**Comment by Serial-ATA** [comment]
`02.ogg` has the wrong extention, it's actually an opus file which is why it's not working. You'll have to use `read_from` with that one.

**Comment by Serial-ATA** [comment]
`07 Rewizja.mp3` fixed in https://github.com/Serial-ATA/lofty-rs/commit/5b9b97784ae419d1833329ee24a33b754b27801f

**Comment by Serial-ATA** [comment]
I'm going to move the last file (`008_Star_Force_tom_6.mp3`) to its own issue, so it's easier to find.
