### ISSUE TITLE
Deal with m4a files processed by Musicbrains Picard

### ISSUE THREAD

**Issue by jimmac** [Serial-ATA/lofty-rs#48]
Attached is a sample file that was processed by [Musicbrains Picard](https://flathub.org/apps/details/org.musicbrainz.Picard) to get the album art embedded. While it usually does the job, there are a few albums that this process made the music files unplayable in [Amberol](https://flathub.org/apps/details/io.bassi.Amberol) (uses lofty). 

It may well be that the music files processed are invalid, but they do seem to be parsed correctly for album art in [Nautilus](https://apps.gnome.org/app/org.gnome.Nautilus/) and played back in [Totem](https://apps.gnome.org/app/org.gnome.Totem/)

[sample-files.zip](https://github.com/Serial-ATA/lofty-rs/files/8655660/sample-files.zip)
.

**Comment by ebassi** [comment]
The error reported by `lofty::read_from_path()` is:

```
MP4 Atom: Expected atom "data" to follow name
```

**Comment by Serial-ATA** [comment]
Thanks for the report! The file is perfectly valid, I just never got around to supporting atoms with multiple values. I'll get on it :)

**Comment by Serial-ATA** [comment]
Implemented in https://github.com/Serial-ATA/lofty-rs/commit/b5478d1f1dc3a8232664e1a47691156a0e4f7cc5, a new release will be coming soon. :smile:
