### ISSUE TITLE
GOG soundtrack fails at text decoding

### ISSUE THREAD

**Issue by Serial-ATA** [Serial-ATA/lofty-rs#53]
**Describe the bug**
`TextDecode("UTF-16 string has an invalid byte order mark")`

**Assets**
[008_Star_Force_tom_6.mp3.zip](https://github.com/Serial-ATA/lofty-rs/files/8645697/008_Star_Force_tom_6.mp3.zip)

**Comment by fabriciojardim** [comment]
Looks like this is causing an issue with Amberol:

https://gitlab.gnome.org/World/amberol/-/issues/113

https://gitlab.gnome.org/World/amberol/-/issues/116
