### ISSUE TITLE
Crash when opening aiff file

### ISSUE THREAD

**Issue by qarmin** [Serial-ATA/lofty-rs#56]
**Describe the bug**
Opening by `read_from` crashes library

```
thread '<unnamed>' panicked at 'attempt to divide by zero', /home/rafal/.cargo/git/checkouts/lofty-rs-f5e48f8219b271cf/03276db/src/iff/aiff/properties.rs:58:18
```

[a.aiff.zip](https://github.com/Serial-ATA/lofty-rs/files/8951888/a.aiff.zip)

**Comment by Serial-ATA** [comment]
Is that the correct file? I'm able to read the file without issue, and your panic says it's occurring in an AIFF file.
