### ISSUE TITLE
Please support ADTS encapsulated track (.aac files)

### ISSUE THREAD

**Issue by vapormusic** [Serial-ATA/lofty-rs#58]
### Summary

Many of our files are .aac files, which is encoded in ADTS. 

Note : https://github.com/taglib/taglib/pull/856/files

**Comment by Serial-ATA** [comment]
Sure, I'll look into this for 0.9.0 :slightly_smiling_face:.

**Comment by Serial-ATA** [comment]
@vapormusic Could you checkout #71 to see if everything is working as expected?

**Comment by Serial-ATA** [comment]
Its been two weeks, so I'll just merge #71 as is.
