### ISSUE TITLE
Album art not detected for .ogg files

### ISSUE THREAD

**Issue by Syzygianinfern0** [Serial-ATA/lofty-rs#60]
### Reproducer

The music album art does not show up in Amberol, but it shows up in other media players such as VLC, MPV, and Gnome Music for OGG files alone.

### Summary

Coming from an amberol issue I raised earlier: https://gitlab.gnome.org/World/amberol/-/issues/216

### Expected behavior

Album art should be visible. 

#### Artwork in Amberol

![image](https://user-images.githubusercontent.com/31875325/182586634-4a7e4efb-0cb2-4e51-befc-001d5f429f32.png)

#### Artwork in MPV

![image](https://user-images.githubusercontent.com/31875325/182586643-2daac089-023d-4bb9-899c-6306e080cb92.png)

**Comment by Serial-ATA** [comment]
Thanks! Are you able to provide the file causing the issue?

**Comment by Syzygianinfern0** [comment]
@Serial-ATA [Here](https://drive.google.com/file/d/1ftHDifXszPgih8eQhh1TCyZ8HjCq0kid/view?usp=sharing) you go!

**Comment by Syzygianinfern0** [comment]
@Serial-ATA, I see you have pushed a fix. Thank you very much!!

How can I get this to work on my side?

**Comment by Serial-ATA** [comment]
I'll be publishing 0.8.0 this week, afterwards it's just a matter of Amberol updating 🙂.

**Comment by Syzygianinfern0** [comment]
Thanks!
