### ISSUE TITLE
Missing ID3v2 data from mp3 files with multiple tags

### ISSUE THREAD

**Issue by caprica** [Serial-ATA/lofty-rs#87]
### Reproducer

I tried this code:

```rust
fn main() {
    let tagged_file = get_tagged_file(&PathBuf::from("some.mp3"));

    for t in tagged_file.tags() {
        println!(" {:?} ", t.tag_type());
        for i in t.items() {
            println!("  {:?} -> {}", i.key(), i.value().text().unwrap_or_else(|| "<no value>"));
        }
        println!();
    }
}
```

### Summary

Some mp3 files I am testing with seem to have multiple ID3v2 tags within them. The files I am testing are out there in the wild, I did not create them or tag them myself.

In the debugger, I can see both ID3v2 tags being decoded and parsed correctly (see screenshots).

The first contains all the interesting information, like album name, artist, title, track number and so on.

The second tag contains only the information I am not interested in, i.e. "EncoderSettings -> Lavf.58.12.100".

It seems the decoding of the second ID3v2 tag completely replaces the previously parsed tag.

The output of the code above is this (I omitted the APE tag dump):

```
 ID3v2 
  EncoderSettings -> Lavf58.12.100

 ID3v1 
  TrackTitle -> [redacted]
  TrackArtist -> [redacted]
  AlbumTitle -> [redacted]
  Year -> 2022
  Comment -> Blah
  TrackNumber -> 13
```

You can see the ID3v2 tag dump contains only the EncoderSettings value.

The reason for my project and why I was looking at this library is to clean up situations like this.

### Expected behavior

The data from all tags should be available, right now with such files it is impossible to get all the tag data with this library.

### Assets

Debugger, first ID3v2 tag:

![image](https://user-images.githubusercontent.com/1385879/209655283-e9d4de0a-6e2a-47e0-b7f2-1aa11497b51e.png)

Debugger, second ID3v2 tag:

![image](https://user-images.githubusercontent.com/1385879/209655440-a5f4448a-368f-4b51-b352-3a83634a78ab.png)

I can't provide a sample mp3 file, sorry, as it is copyrighted material.

**Comment by Serial-ATA** [comment]
Hello! Could you see if #88 fixes the issue? :)

**Comment by caprica** [comment]
Hi, I had to hack my code around a bit because of the Cow changes on getters, but yes, this seems to now merge both ID3v2 tags when I test the same mp3 files I used for the original report.

Thank you very much.

**Comment by Serial-ATA** [comment]
Yeah, the `Cow` change is an unfortunate side effect of #82 because ID3v2 couldn't maintain a consistent spec between versions. I may find another solution before releasing 0.10.0.

Thanks for the report!
