### ISSUE TITLE
Build with feature "id3v2" enabled and "id3v1" disabled fails

### ISSUE THREAD

**Issue by uklotzde** [Serial-ATA/lofty-rs#89]
### Summary

Discovered while selectively enabling features starting from `default-features = false`.

**Comment by Serial-ATA** [comment]
I've been considering just removing the features for awhile now, they haven't been tested in months. They're from a time when they actually added extra dependencies. I'll remove them in the next release with the exception of one for ID3v2's optional compression which adds `flate2`.

**Comment by uklotzde** [comment]
That's fine.

I am currently investigating if it is feasible to migrate from `id3`, `mp4ameta`, `metaflac`, ... to `lofty-rs`. Dealing with all the low-level details and compatibility/interoperability issues is tedious.
