### ISSUE TITLE
Improve interoperability between DJ applications

### ISSUE THREAD

**Issue by uklotzde** [Serial-ATA/lofty-rs#90]
For interoperability between different DJ applications the following post and metadata mapping matrix might be helpful:

https://www.reddit.com/r/Beatmatch/comments/sleokj/proposed_standard_for_metadata_compatibility_in/
https://docs.google.com/spreadsheets/d/1zhIJPOtYIueV72Gd81aVnbSa6dIA-azq9fnGC2rHUzo/edit#gid=68428938

I have noticed that some tag keys are not yet covered by lofty-rs, e.g. `MIXARTIST` in Vorbis Comments.

**Comment by Serial-ATA** [comment]
It looks like `REMIXER` is the more popular key in Vorbis Comments. `MIXARTIST` can definitely be recognized as `ItemKey::Remixer`, but I'd rather write the keys that are most popular.

Other missing keys: `color`, `TIPL:producer` (#91), `InitialKey` for formats other than ID3v2
